### ISSUE TITLE
Failing on aws-sdk2 applications

### ISSUE THREAD

**Issue by maxgamurar** [newrelic/node-newrelic-aws-sdk#267]
Message: Cannot read properties of undefined (reading 'MessageSpec'). Stack: TypeError: Cannot read properties of undefined (reading 'MessageSpec')

    at getSqsSpec (/edetek/node-api/node_modules/@newrelic/aws-sdk/lib/v3/sqs.js:45:25)

    at recordProd (/edetek/node-api/node_modules/newrelic/lib/shim/message-shim.js:288:33)

    at wrapper (/edetek/node-api/node_modules/newrelic/lib/shim/shim.js:850:33)

    at SQSClient.send (/edetek/node-api/node_modules/@smithy/smithy-client/dist-cjs/client.js:20:20)

    at SQSClient.wrappedSend (/edetek/node-api/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:63:17)

**Comment by bizob2828** [comment]
@maxgamurar which version of the newrelic agent are you on?

**Comment by maxgamurar** [comment]
newrelic@11.1.0. 
Its started since update of "@newrelic/aws-sdk": "^7.0.0" to @newrelic/aws-sdk": "^7.2.0

**Comment by bizob2828** [comment]
@maxgamurar can you upgrade newelic to 11.11.0?

**Comment by maxgamurar** [comment]
@bizob2828  11.11.0 works fine..
not sure if we need to mark ver 11.1.0 as deprecated, but its up 2 u guys. Thanks!

**Comment by bizob2828** [comment]
@maxgamurar yea we're talking internally about what to do.  The separate packages do not really serve a purpose any longer since they cannot be run as standalone and are bundled with the agent.  I'm going to close this for now
